export interface StaticCourse {
  id: string;
  title: string;
  description: string;
  category: string;
  lectureCount: number;
  speakerName: string;
  students: number;
  rating: number;
  level: string;
  freeUrl: string;
  modules: string[];
}

export const STATIC_COURSES: StaticCourse[] = [
  {
    id: "quran-tajweed",
    title: "Quran Recitation with Tajweed",
    description: "Master the rules of Tajweed for beautiful, correct Quran recitation. Covers Makharij al-Huruf, Sifat, Noon Sakinah, Meem Sakinah, and Madd rules.",
    category: "Quran Recitation",
    lectureCount: 24,
    speakerName: "Sheikh Yusuf Zidan",
    students: 3200,
    rating: 4.9,
    level: "Beginner",
    freeUrl: "https://www.youtube.com/results?search_query=quran+recitation+tajweed+full+course+beginners+makharij",
    modules: [
      "Introduction to Tajweed & its importance",
      "Makharij al-Huruf — Articulation Points",
      "Sifaat al-Huruf — Letter Characteristics",
      "Noon Sakinah & Tanween Rules",
      "Meem Sakinah Rules",
      "Rules of Laam — Tafkheem & Tarqeeq",
      "Rules of Raa — Heavy & Light",
      "Madd — Lengthening Rules (Natural & Artificial)",
      "Waqf & Ibtidaa — Stopping & Starting",
      "Qalqalah — Echo Pronunciation",
      "Hamzah Wasl & Qat",
      "Common Mistakes & Corrections",
      "Practical Recitation — Al-Fatiha",
      "Practical Recitation — Juz Amma",
      "Advanced Madd Applications",
      "Applying Tajweed in Salah",
    ],
  },
  {
    id: "tafseer-juz-amma",
    title: "Tafseer of Juz Amma",
    description: "Deep explanation of the 30th Juz of the Quran. Learn the meaning, context, and lessons of the most commonly recited surahs in Salah.",
    category: "Tafseer",
    lectureCount: 18,
    speakerName: "Dr. Bilal Philips",
    students: 4100,
    rating: 4.8,
    level: "Beginner",
    freeUrl: "https://www.youtube.com/results?search_query=tafseer+juz+amma+dr+bilal+philips",
    modules: [
      "Introduction to Tafseer methodology",
      "Surah An-Naba — The Great News",
      "Surah An-Nazi'at — Those Who Pull Out",
      "Surah Abasa — He Frowned",
      "Surah At-Takwir — The Folding Up",
      "Surah Al-Infitar & Al-Mutaffifin",
      "Surah Al-Inshiqaq — The Splitting Open",
      "Surah Al-Buruj & At-Tariq",
      "Surah Al-Ala & Al-Ghashiyah",
      "Surah Al-Fajr & Al-Balad",
      "Surah Ash-Shams through Ad-Duha",
      "Surah Al-Inshirah & At-Tin",
      "Surah Al-Alaq — First Revelation",
      "Surah Al-Qadr & Al-Bayyinah",
      "Surah Az-Zalzalah through Al-Asr",
      "Surah Al-Humazah through Al-Falaq & An-Nas",
    ],
  },
  {
    id: "fiqh-salah",
    title: "Fiqh of Salah — Complete Guide",
    description: "Complete Islamic jurisprudence of prayer — conditions, pillars, obligations, Sunnah acts, and invalidators. Based on classical Fiqh sources.",
    category: "Fiqh",
    lectureCount: 16,
    speakerName: "Mufti Menk",
    students: 5800,
    rating: 4.9,
    level: "Beginner",
    freeUrl: "https://www.youtube.com/results?search_query=fiqh+salah+complete+mufti+menk",
    modules: [
      "Introduction — Why Salah is the pillar of Deen",
      "Conditions (Shuroot) of Salah",
      "Taharah — Wudu, Ghusl & Tayammum",
      "Qiblah — Facing the direction of prayer",
      "Pillars (Arkan) of Salah",
      "Obligatory Acts (Waajibaat) of Salah",
      "Sunnah Acts & their rewards",
      "Makruh & impermissible acts in Salah",
      "Fard Prayers — Timings & Rak'ahs",
      "Sunnah Mu'akkadah & Nawafil",
      "Jama'ah (Congregational) Prayer",
      "Friday Jumu'ah — Fiqh & Conditions",
      "Qada — Making up Missed Prayers",
      "Salah for the Sick & Traveller",
      "Common Errors & Corrections",
      "Strengthening Khushoo' in Prayer",
    ],
  },
  {
    id: "aqeedah-101",
    title: "Islamic Aqeedah: Pillars of Faith",
    description: "Comprehensive course on Islamic creed — belief in Allah, Angels, Books, Prophets, Day of Judgement, and Divine Decree (Qadar). Based on Aqeedah al-Wasitiyyah.",
    category: "Aqeedah",
    lectureCount: 22,
    speakerName: "Sheikh Assim al-Hakeem",
    students: 2900,
    rating: 4.8,
    level: "Intermediate",
    freeUrl: "https://www.youtube.com/results?search_query=aqeedah+pillars+of+faith+assim+al+hakeem",
    modules: [
      "What is Aqeedah and why does it matter?",
      "Tawheed — Oneness of Allah (Al-Uluhiyyah)",
      "Tawheed Ar-Rububiyyah — Lordship of Allah",
      "Tawheed Al-Asma was-Sifaat — Names & Attributes",
      "Belief in the Angels",
      "Belief in the Divine Books",
      "Belief in the Prophets & Messengers",
      "Khatam an-Nabiyyin — Seal of Prophethood",
      "Belief in the Day of Judgement",
      "Signs of the Hour — Minor & Major",
      "The Barzakh — Life in the Grave",
      "Al-Hashr — The Gathering & Reckoning",
      "Jannah & Jahannam",
      "Belief in Al-Qadar (Divine Decree)",
      "Ash'ari & Maturidi — Historical Context",
      "Common Deviations in Aqeedah",
      "Protecting Iman from doubts",
    ],
  },
  {
    id: "hadith-nawawi",
    title: "40 Hadith of Imam Nawawi",
    description: "Study the 40 most important hadith of Imam Nawawi — the foundational texts of Islamic ethics, worship, and character. Essential for every Muslim.",
    category: "Hadith",
    lectureCount: 20,
    speakerName: "Sheikh Omar Suleiman",
    students: 6200,
    rating: 4.9,
    level: "All Levels",
    freeUrl: "https://www.youtube.com/results?search_query=40+hadith+nawawi+omar+suleiman",
    modules: [
      "Introduction — The 40 Hadith & Imam Nawawi",
      "Hadith 1 — Actions by intentions (Niyyah)",
      "Hadith 2 — Islam, Iman & Ihsan",
      "Hadith 3 — Pillars of Islam",
      "Hadith 4 — Creation of the human being",
      "Hadith 5 — Innovation in religion (Bid'ah)",
      "Hadith 6 — Halal & Haram are clear",
      "Hadith 7 — Religion is sincere advice",
      "Hadith 8 — Fighting the Muslim",
      "Hadith 9 — Capability & obligation",
      "Hadith 10 — Pure things are permissible",
      "Hadith 12 — Leaving what does not concern you",
      "Hadith 13 — Loving for the brother what you love for yourself",
      "Hadith 16 — Do not become angry",
      "Hadith 17 — Excellence in all things",
      "Hadith 19 — Be mindful of Allah",
      "Hadith 27 — Righteousness is good character",
      "Hadith 29 — Acts that enter Jannah",
      "Hadith 35 — Do not envy one another",
      "Hadith 42 — Forgiveness & Allah's mercy",
    ],
  },
  {
    id: "tazkiyah-soul",
    title: "Purification of the Soul (Tazkiyah)",
    description: "Journey through Islamic spirituality — purify the heart from diseases like pride, envy, and anger. Based on Imam al-Ghazali's Ihya Ulum al-Din.",
    category: "Spirituality",
    lectureCount: 28,
    speakerName: "Sheikh Hamza Yusuf",
    students: 3700,
    rating: 4.9,
    level: "Intermediate",
    freeUrl: "https://www.youtube.com/results?search_query=purification+soul+tazkiyah+hamza+yusuf",
    modules: [
      "Introduction to Tazkiyah — the science of the heart",
      "The heart (Qalb) in Islam — its nature",
      "The sick heart, dead heart & living heart",
      "Diseases of the heart — overview",
      "Kibr — Pride & arrogance",
      "Hasad — Envy & its cure",
      "Riya — Showing off & its dangers",
      "Anger (Ghadab) — causes and control",
      "Love of the dunya — causes and cure",
      "Stinginess (Bukhl) & its treatment",
      "Heedlessness (Ghaflah)",
      "The virtues of Tawbah — sincere repentance",
      "Sabr — Patience in all its forms",
      "Shukr — True gratitude to Allah",
      "Tawakkul — Reliance on Allah",
      "Muhasabah — Self-accounting",
      "Muraqabah — Vigilance & awareness of Allah",
      "Dhikr — Its power and practice",
      "The role of du'a in purification",
      "Companionship & its effect on the soul",
    ],
  },
  {
    id: "seerah-prophet",
    title: "Seerah: Life of the Prophet ﷺ",
    description: "Complete biography of Prophet Muhammad ﷺ from birth to his passing. Makkah period, Hijra, Madinah period, major battles, and lessons for modern Muslims.",
    category: "Islamic History",
    lectureCount: 32,
    speakerName: "Sheikh Yasir Qadhi",
    students: 8100,
    rating: 5.0,
    level: "All Levels",
    freeUrl: "https://www.youtube.com/results?search_query=seerah+life+of+prophet+yasir+qadhi",
    modules: [
      "Pre-Islamic Arabia — Background & context",
      "Birth of the Prophet ﷺ — Year of the Elephant",
      "Childhood & youth — Khadijah & early life",
      "First Revelation — The Cave of Hira",
      "Early Islam in Makkah — secret preaching",
      "Open preaching & Quraysh's opposition",
      "The first Muslims & their sacrifices",
      "Persecution of the believers",
      "Migration to Abyssinia — two Hijrahs",
      "Year of Sorrow — death of Khadijah & Abu Talib",
      "Isra & Mi'raj — the Night Journey",
      "The Hijra to Madinah",
      "Building the Islamic state in Madinah",
      "The Constitution of Madinah",
      "Battle of Badr — first major battle",
      "Battle of Uhud — lessons from defeat",
      "Battle of the Trench (Khandaq)",
      "Treaty of Hudaybiyyah",
      "Conquest of Makkah",
      "Battle of Hunayn & Tabuk",
      "The Farewell Pilgrimage",
      "The passing of the Prophet ﷺ",
    ],
  },
  {
    id: "arabic-word-to-word",
    title: "Word-to-Word Quran Arabic",
    description: "Understand every word of the Quran in Arabic. Learn grammatical structures, root words, and vocabulary so you can understand Quran directly without translation.",
    category: "Word-to-Word",
    lectureCount: 40,
    speakerName: "Dr. V. Abdur Rahim",
    students: 4400,
    rating: 4.8,
    level: "Beginner–Intermediate",
    freeUrl: "https://www.youtube.com/results?search_query=word+to+word+quran+arabic+v+abdur+rahim",
    modules: [
      "Arabic alphabet & vowel marks (harakat)",
      "Connecting letters — joining rules",
      "Nouns (Ism) — definite & indefinite",
      "Pronouns — He, She, They, You, I",
      "Verbs (Fi'l) — past, present, command",
      "Root word system — the 3-letter root",
      "Verb forms (Awzan) — patterns",
      "Prepositions (Huroof al-Jarr)",
      "Sentence structure — Jumlah Ismiyyah & Fi'liyyah",
      "Al-Fatiha — word-by-word analysis",
      "Ayat al-Kursi — word-by-word",
      "Last 10 Surahs — vocabulary",
      "Common Quranic words (100 most frequent)",
      "Dual & plural forms",
      "Quranic grammar — Irab basics",
      "Reading Surah Al-Baqarah verse-by-verse",
      "Reading Surah Al-Mulk verse-by-verse",
      "Reading Surah Yaseen verse-by-verse",
      "Building vocabulary systematically",
      "Reading Quran with understanding",
    ],
  },
  {
    id: "fiqh-zakat",
    title: "Fiqh of Zakat & Islamic Finance",
    description: "Master the rulings of Zakat, Sadaqah, and Islamic financial transactions. Includes halal investments, avoiding riba, and contemporary Fiqh issues.",
    category: "Fiqh",
    lectureCount: 14,
    speakerName: "Sheikh Shafi Chowdhury",
    students: 2100,
    rating: 4.7,
    level: "Intermediate",
    freeUrl: "https://www.youtube.com/results?search_query=fiqh+zakat+islamic+finance+halal+investments",
    modules: [
      "Introduction to Zakat — its importance",
      "Nisab — the minimum threshold",
      "Zakat on gold, silver & cash",
      "Zakat on business inventory & trade goods",
      "Zakat on agricultural produce",
      "Zakat on stocks & investments",
      "The 8 categories eligible to receive Zakat",
      "Sadaqah al-Fitr (Fitrana)",
      "Riba — definition, types & prohibition",
      "Halal mortgages & home financing",
      "Islamic investment — stocks & funds",
      "Cryptocurrency — Islamic perspective",
      "Business partnerships (Musharakah & Mudarabah)",
      "Contemporary Fiqh questions in finance",
    ],
  },
  {
    id: "tafseer-ibn-katheer",
    title: "Tafseer Ibn Katheer — Selected Surahs",
    description: "In-depth Tafseer from the classical masterwork of Ibn Katheer. Covers Al-Baqarah, Al-Imran, Al-Kahf, Al-Mulk, and Yaseen with detailed commentary.",
    category: "Tafseer",
    lectureCount: 36,
    speakerName: "Sheikh Imad Khalil",
    students: 2800,
    rating: 4.9,
    level: "Intermediate",
    freeUrl: "https://www.youtube.com/results?search_query=tafseer+ibn+katheer+al+baqarah+al+kahf",
    modules: [
      "Ibn Katheer — the man and his methodology",
      "Al-Baqarah — The Cow (Part 1: 1–20)",
      "Al-Baqarah — Ayat al-Kursi (255–257)",
      "Al-Baqarah — Last two ayat (285–286)",
      "Al-Imran — The Family of Imran (1–50)",
      "Al-Imran — Battle of Uhud context",
      "Al-Kahf — The Cave (1–18) & the Sleepers",
      "Al-Kahf — Dhul Qarnayn & Gog Magog",
      "Al-Kahf — Musa & Khidr (60–82)",
      "Surah Yaseen — the heart of the Quran",
      "Yaseen — Resurrection & signs of Allah",
      "Surah Al-Mulk — Sovereignty",
      "Al-Mulk — Death, life & accountability",
      "Surah Al-Rahman — The Beneficent",
      "Surah Al-Waqiah — The Event",
      "Surah Al-Muzzammil & Al-Muddaththir",
    ],
  },
  {
    id: "islamic-history-caliphs",
    title: "The Rightly Guided Caliphs",
    description: "History of Abu Bakr, Umar, Uthman, and Ali (RA) — their leadership, challenges, conquests, and lasting legacy for the Muslim ummah.",
    category: "Islamic History",
    lectureCount: 20,
    speakerName: "Sheikh Abdul Nasir Jangda",
    students: 3500,
    rating: 4.8,
    level: "All Levels",
    freeUrl: "https://www.youtube.com/results?search_query=rightly+guided+caliphs+history+abdul+nasir+jangda",
    modules: [
      "The concept of Khilafah in Islam",
      "Abu Bakr al-Siddiq (RA) — character & background",
      "The Riddah Wars — fighting the apostates",
      "Compilation of the Quran under Abu Bakr",
      "The passing of Abu Bakr al-Siddiq (RA)",
      "Umar ibn al-Khattab (RA) — early life",
      "The expansion of the Islamic state",
      "Conquest of Jerusalem under Umar",
      "Administrative genius — Umar's legacy",
      "The passing of Umar ibn al-Khattab (RA)",
      "Uthman ibn Affan (RA) — the generous Caliph",
      "Compilation of the Mushaf under Uthman",
      "The Fitnah — causes of the rebellion",
      "The passing of Uthman ibn Affan (RA)",
      "Ali ibn Abi Talib (RA) — the lion of Allah",
      "The Battle of the Camel & Siffin",
      "The assassination of Ali (RA)",
      "Hasan ibn Ali & the end of the Rashidun",
      "Lessons from the Rightly Guided Caliphs",
      "Their legacy for the Muslim world today",
    ],
  },
  {
    id: "aqeedah-names-attributes",
    title: "99 Names of Allah — Deep Dive",
    description: "Explore the 99 beautiful names and attributes of Allah (Asmaul Husna). Understand their meaning, implications for worship, and how to incorporate them into daily life.",
    category: "Aqeedah",
    lectureCount: 15,
    speakerName: "Sheikh Omar Suleiman",
    students: 4900,
    rating: 4.9,
    level: "Beginner",
    freeUrl: "https://www.youtube.com/results?search_query=99+names+allah+asmaul+husna+omar+suleiman",
    modules: [
      "Introduction — What are the Asmaul Husna?",
      "Ar-Rahman & Ar-Raheem — The Most Merciful",
      "Al-Malik, Al-Quddus, As-Salam",
      "Al-Mu'min, Al-Muhaymin, Al-Aziz",
      "Al-Jabbar, Al-Mutakabbir",
      "Al-Khaliq, Al-Bari, Al-Musawwir",
      "Al-Ghaffar, Al-Qahhaar, Al-Wahhab",
      "Ar-Razzaq, Al-Fattah, Al-Aleem",
      "Al-Qabid & Al-Basit — The One who withholds and expands",
      "Al-Baseer & As-Samee' — All-seeing, All-hearing",
      "Al-Hakam, Al-Adl, Al-Lateef, Al-Khabeer",
      "Al-Haleem, Al-Adheem, Al-Ghafoor, Ash-Shakoor",
      "Al-Ali, Al-Kabeer, Al-Hafidh, Al-Muqeet",
      "Al-Hasib, Al-Jaleel, Al-Kareem, Ar-Raqeeb",
      "Al-Mujib, Al-Wasi, Al-Hakeem, Al-Wadood",
    ],
  },
];

export const WHAT_YOU_LEARN: Record<string, string[]> = {
  "Quran Recitation": ["Proper Tajweed rules", "Makhaarij (articulation points)", "Sifaat of letters", "Practical recitation exercises"],
  "Tafseer": ["Arabic Quranic vocabulary", "Classical Tafseer methodology", "Historical context of revelations", "Applying Quranic lessons"],
  "Fiqh": ["Foundational rulings in Islamic law", "Evidence from Quran & Sunnah", "Scholarly consensus & differences", "Application in daily life"],
  "Aqeedah": ["The six pillars of Iman", "Names & Attributes of Allah", "Common misconceptions corrected", "Strengthening your conviction"],
  "Hadith": ["Hadith classification methodology", "Key Hadith collections", "Applying Prophetic Sunnah", "Hadith Sciences terminology"],
  "Spirituality": ["Purification of the heart", "Dhikr and worship routines", "Islamic ethics and character", "Overcoming spiritual hardships"],
  "Islamic History": ["Seerah of the Prophet ﷺ", "Companion biographies", "Early Islamic civilization", "Lessons for the modern Muslim"],
  "Word-to-Word": ["Arabic root word analysis", "Quranic grammar basics", "Building vocabulary systematically", "Understanding Quranic sentences"],
};
